dist: xenial
language: python
python:
- "3.7"
before_install:
- pip install -q coveralls pipenv
install:
- pipenv install --dev
script:
- coverage run -m unittest discover tests
after_success:
- coveralls
